name: Pull request
on:
  pull_request:
    branches: [ main ]
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: policyengine-test
          environment-file: docs/environment.yml
          auto-activate-base: false
      - name: Install package
        shell: bash -l {0}
        run: make install
      - name: Generate documentation
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: make documentation
        env:
          POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN: ${{ secrets.POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN}}