name: Push
on:
  push:
    branches: [ main ]
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    if: |
      (github.repository == 'masterismail/policyengine-test')
      && (github.event.head_commit.message == 'Update PolicyEngine UK')
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: policyengine-test
          environment-file: environment.yml
          auto-activate-base: false
      - name: Install package
        shell: bash -l {0}
        run: make install
      - name: Generate documentation
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: make documentation
      - name: Deploy documentation
        if: matrix.os == 'ubuntu-latest'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: docs/_build/html  # The folder the action should deploy.